name: 📦 Release

on:
  push:
    tags:
      - '*'

jobs:
  npm:
    name: 📦 Release on NPM
    runs-on: ubuntu-latest
    steps:
      - name: ⸙ Checkout
        uses: actions/checkout@v3
      - name: 👷 Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          cache: true
      - name:  ⚙️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 18
          scope: '@netresearch'
          tag: latest
          access: public
      - name: ⚡ Install dependencies
        run: pnpm install --frozen-lockfile
      - name: 🔨 Build
        run: pnpm build
      - name: ☁️ Publish on NPM
        run: pnpm publish --access public --tag latest --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  github:
    name: 🚀 Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 📎 Generate Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: generate_changelog
      - name: 🗞 Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.generate_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
